# Site settings
title: Trident Bioscience, Inc.
description: Optimized biology.
baseurl: ""
url: "tridentbio.github.io"

# User settings
username: Trident Bioscience, Inc.
email: info@trident.bio

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
